apiVersion: v1
kind: Service
metadata:
  name: fake-api-service
  labels:
    app: fake-api
spec:
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: http
  selector:
    app: fake-api
