apiVersion: v1
kind: Service
metadata:
  name: fake-api-service
  labels:
    app: fake-api
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: fake-api
